name: Jamie Fawcett
markdown: kramdown

#Setup collections so that md can be pushed into pages
collections:
  projects:
    output: true
    permalink: /project/:name
  publications:
    output: False
  talks:
    output: False
  resume-employment:
    output: False
  resume-education:
    output: False
collections_dir: content

#Setup the sass print style + set location (actually default)
sass:
    sass_dir : _sass
    style: compressed
