name: Jamie Fawcett
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /project/:name
    #collections_dir: content
  publications:
    output: False
  talks:
    output: False
