name: Jamie Fawcett
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /project/:name
  publications:
    output: False
  talks:
    output: False
  resume-employment:
    output: False
  resume-education:
    output: False
collections_dir: content
