#Description stuff (esp for SEO)
title: Jamie Fawcett
description: Data science, Data governance, Data policy
url: https://www.jamiefawcett.ca/

twitter:
  username: jamiefawcett1
  card: summary
#logo
social:
  name: Jamie Fawcett
  links:
    - https://www.linkedin.com/in/jamie-fawcett-737314a3/
    - https://github.com/JmeF
    - https://scholar.google.com/citations?user=nDXweXQAAAAJ
    - https://www.flickr.com/photos/129714065@N05/

lang: en_CA

#plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

#set the markdown
markdown: kramdown

#Setup collections so that md can be pushed into pages
collections:
  projects:
    output: true
    permalink: /project/:name
  publications:
    output: False
  talks:
    output: False
  resume-employment:
    output: False
  resume-education:
    output: False
  resume-education-grad:
    output: False
  resume-part-time:
    output: False
collections_dir: content

#Setup the sass print style + set location (actually default)
sass:
    sass_dir : _sass
    style: compressed
